/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import BancoDeDados.Persistencia;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import modelo.Cliente;
import modeloDAO.ClienteDAO;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;


public class TelaCliente extends javax.swing.JFrame{
    private Inicial telaPai;
    private Cliente cliente2;
    private TelaVenda telaVenda;
    
    MaskFormatter mData = new MaskFormatter();
    MaskFormatter mTel = new MaskFormatter();
    MaskFormatter mRG = new MaskFormatter();
    /**
     * Creates new form TelaPaciente
     */
    public TelaCliente(Inicial inicial,Cliente cliente, TelaVenda telaVenda) {
       cliente2 = cliente;
       this.telaVenda = telaVenda;
       try{
            mData.setMask("##/##/####");
            mData.setPlaceholderCharacter('_');
            mTel.setMask("(##) ####-####");
            mTel.setPlaceholderCharacter('_');
            mRG.setMask("##.###.###-#");
            mRG.setPlaceholderCharacter('_');
       }catch(Exception e){}
       initComponents();
       telaPai = inicial;
        this.setLocationRelativeTo(null);
        
        if(cliente!=null){
            nick.setText(cliente.getLogin());
            senha.setText(cliente.getSenha());
            nome.setText(cliente.getNome());
            rg.setText(String.valueOf(cliente.getRg()));
         
            data.setText(String.valueOf(cliente.getData_nascimento()));
            endereco.setText(cliente.getEndereco());
            tel.setText(cliente.getTelefone());
            nick.setEditable(false);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        rg = new JFormattedTextField(mRG);
        endereco = new javax.swing.JTextField();
        nick = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();
        tel = new JFormattedTextField(mTel);
        data = new JFormattedTextField(mData);

        jPasswordField2.setText("jPasswordField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Cadastro Cliente");

        jLabel2.setText("Nome:*");

        jLabel4.setText("Telefone:");

        jLabel6.setText("RG:*");

        jLabel7.setText("Endereço:");

        jLabel8.setText("Nickname:*");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        rg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgActionPerformed(evt);
            }
        });

        jLabel10.setText("Data de Nasc.:*");

        jLabel13.setText("*: Campos Obrigatórios");

        jLabel14.setText("Senha:*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jLabel8)
                            .addGap(10, 10, 10)
                            .addComponent(nick, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(jLabel14)
                            .addGap(10, 10, 10)
                            .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addComponent(jLabel2)
                            .addGap(10, 10, 10)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(jLabel4)
                            .addGap(10, 10, 10)
                            .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addComponent(jLabel6)
                            .addGap(10, 10, 10)
                            .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(131, 131, 131)
                            .addComponent(jButton2))
                        .addComponent(jLabel13)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(10, 10, 10)
                            .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addComponent(nick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel14))
                    .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean ok = true;
        String msg="";
        
        if (nick.getText().length()==0){
            ok=false;
            msg +="Preencha o campo Nick corretamente.\n";
        }
              if (senha.getText().length()==0){
            ok=false;
            msg +="Preencha o campo Senha corretamente.\n";
        }
               if (rg.getText().length()==0){
            ok=false;
            msg +="Preencha o campo RG corretamente.\n";
        }
            if (rg.getText().matches("^[a-zA-Z]*$")){
            ok=false;
            msg +="Preencha o campo RG corretamente.\n";
        } 
              if (data.getText().length()==0){
            ok=false;
            msg +="Preencha o campo Data de nascimento corretamente.\n";
        }
              if (data.getText().matches("^[a-zA-Z]*$")){
            ok=false;
            msg +="Preencha o campo Data de nascimento corretamente.\n";
        } 
                 if (tel.getText().matches("^[a-zA-Z]*$")){
            ok=false;
            msg +="Preencha o campo Telefone corretamente.\n";
        } 
              if (nome.getText().length()==0){
            ok=false;
            msg +="Preencha o campo Nome corretamente.\n";
        }
                 if (nome.getText().matches("^[0-9]*$")){
            ok=false;
            msg +="Preencha o campo Nome corretamente.\n";
        }
            if (cliente2==null){
                    List<Cliente> clientes = Persistencia.listar(new Cliente());
                 for(Cliente cliente: clientes){
                     if (cliente.getLogin().equals(nick.getText())){
                           ok=false;
            msg +="Nickname já existe.\n";
                     }
                         
                 }       
              
            }
               
        
        if(!ok){
            JOptionPane.showMessageDialog(this,"Atenção..\n"+msg);
        }
        else{
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date data_nasc = null;
            try {
                data_nasc = sdf.parse(data.getText());
            } catch (ParseException ex) {
            }
            Cliente p  = new Cliente(nick.getText(),senha.getPassword().toString(),nome.getText(),
                 tel.getText(),rg.getText(), endereco.getText(),data_nasc);
            
                ClienteDAO c = new ClienteDAO();
          
                if (cliente2==null){
           
                    if (c.salvar(p)){
                        JOptionPane.showMessageDialog(this,"Cliente cadastrado!");
                        this.dispose();
                        telaPai.preencheTabelaCliente();
                        if (telaVenda != null){
                            telaVenda.getComboCLiente().addItem(p.getNome());
                            telaVenda.getComboCLiente().setSelectedItem(p.getNome());
                        }
                    }
                    else{
                    JOptionPane.showMessageDialog(this,"Não foi possivel cadastrar!");
                    }
                }
                else{
                     if (c.atualizar(p)){
                        JOptionPane.showMessageDialog(this,"Cliente alterado!");
                        this.dispose();
                        telaPai.preencheTabelaCliente();
                     } else {
                        JOptionPane.showMessageDialog(this,"Não foi possivel alterar!");
                     }
                }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(final Inicial inicial, final Cliente cliente, final TelaVenda telaVenda) {
        /* Set the Nimbus look and feel */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente(inicial,cliente, telaVenda).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JFormattedTextField data;
    private javax.swing.JTextField endereco;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField nick;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField rg;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables

}
