package view;

import Controle.GerenciarCliente;
import Controle.GerenciarVenda;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.ProdutoVenda;

public class TelaVenda extends javax.swing.JFrame {
    private Inicial telapai;
    private ProdutoVenda produtoVenda;
    
    public TelaVenda(Cliente cliente, Inicial ini) {
        telapai = ini;
        produtoVenda = new ProdutoVenda();
                
        initComponents();
        if((telapai.getValor()==4) && (cliente!=null)){
            comboCliente.removeAllItems();
            comboCliente.addItem(cliente.getLogin());
            comboCliente.setSelectedItem(cliente.getLogin());
            comboCliente.setEnabled(false);
            
        }else{
            List<Cliente> clientes = GerenciarCliente.buscarTodosClientes();
            comboCliente.removeAllItems();
            if (cliente != null){
                comboCliente.addItem(cliente.getLogin());
                comboCliente.setSelectedItem(cliente.getLogin());
            }else {
                comboCliente.addItem("");
            }
            for (Cliente cli : clientes){
                if (cliente != null){
                    if (!cli.getLogin().equals(cliente.getLogin())){
                        comboCliente.addItem(cli.getNome());
                    }
                }else {
                    comboCliente.addItem(cli.getLogin());
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboCliente = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        incluirProduto = new javax.swing.JButton();
        adicionar = new javax.swing.JButton();
        fecharVenda = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        excluirProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda");

        comboCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Cliente:");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cod", "Nome", "Marca", "Modelo", "Preço", "Qtde"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(20);
        tabela.getColumnModel().getColumn(4).setPreferredWidth(30);
        tabela.getColumnModel().getColumn(5).setPreferredWidth(20);

        incluirProduto.setText("Incluir Produto");
        incluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirProdutoActionPerformed(evt);
            }
        });

        adicionar.setText("Cadastrar");
        adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarActionPerformed(evt);
            }
        });

        fecharVenda.setText("Fechar Venda");
        fecharVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharVendaActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        excluirProduto.setText("Excluir Produto");
        excluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(incluirProduto)
                        .addGap(18, 18, 18)
                        .addComponent(excluirProduto)
                        .addGap(18, 18, 18)
                        .addComponent(fecharVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(adicionar))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(adicionar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(incluirProduto)
                    .addComponent(fecharVenda)
                    .addComponent(cancelar)
                    .addComponent(excluirProduto))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarActionPerformed
        TelaCliente.main(telapai, null, this);
    }//GEN-LAST:event_adicionarActionPerformed

    private void incluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirProdutoActionPerformed
        TelaIncluirProduto.main(null, this, produtoVenda);
    }//GEN-LAST:event_incluirProdutoActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void fecharVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharVendaActionPerformed
        if(!produtoVenda.getItens().isEmpty()){
            if(comboCliente.getSelectedItem() != null){
                Cliente cli = GerenciarCliente.buscarCliente((String)comboCliente.getSelectedItem());
                if (GerenciarVenda.finalizarVenda (cli.getLogin(), produtoVenda)){
                    JOptionPane.showMessageDialog(null, "Venda Realizada com sucesso!");
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Não foi possivel Realizar a venda");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Nenhum cliente selecionado");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Nenhum produto incluido na venda");
        }
    }//GEN-LAST:event_fecharVendaActionPerformed

    private void excluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirProdutoActionPerformed
        if (tabela.getSelectedRow() != -1){
            int linha = tabela.getSelectedRow();
            int i;
            if (tabela.getValueAt(linha, 0) != null ){
                produtoVenda.getItens().remove(produtoVenda.getIten((Long)tabela.getValueAt(linha, 0)));
                for (i=linha; i<tabela.getRowCount()-1; i++){
                    tabela.setValueAt(tabela.getValueAt(i+1, 0), i, 0);
                    tabela.setValueAt(tabela.getValueAt(i+1, 1), i, 1);
                    tabela.setValueAt(tabela.getValueAt(i+1, 2), i, 2);
                    tabela.setValueAt(tabela.getValueAt(i+1, 3), i, 3);
                    tabela.setValueAt(tabela.getValueAt(i+1, 4), i, 4);
                    tabela.setValueAt(tabela.getValueAt(i+1, 5), i, 5);
                }
                tabela.setValueAt(null, i, 0);
                tabela.setValueAt(null, i, 1);
                tabela.setValueAt(null, i, 2);
                tabela.setValueAt(null, i, 3);
                tabela.setValueAt(null, i, 4);
                tabela.setValueAt(null, i, 5);
                if(i>9){
                    DefaultTableModel tableModel = (DefaultTableModel)tabela.getModel();
                    tableModel.setNumRows(tabela.getRowCount()-1);
                }
            }
        }
    }//GEN-LAST:event_excluirProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], final Cliente cliente, final Inicial ini) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda(cliente, ini).setVisible(true);
            }
        });
    }
    
    public javax.swing.JComboBox getComboCLiente(){
        return comboCliente;
    } 
    
    public javax.swing.JTable getTabela(){
        return this.tabela;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionar;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox comboCliente;
    private javax.swing.JButton excluirProduto;
    private javax.swing.JButton fecharVenda;
    private javax.swing.JButton incluirProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
