/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import BancoDeDados.Persistencia;
import Controle.GerenciarCliente;
import Controle.GerenciarUsoMaquina;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modeloDAO.ClienteDAO;
import modeloDAO.ValorHoraDAO;

/**
 *
 * @author Pedro
 */
public class TelaUsoMaquina extends javax.swing.JFrame {
    private DefaultTableModel modelo = new DefaultTableModel();
    private static Inicial telaPai;
    /**
     * Creates new form TelaUsodeMaquina1
     */
    public TelaUsoMaquina() {
        initComponents();
        modelo.setColumnCount(0);
        modelo.addColumn("Login");
        modelo.addColumn("Nome");
        modelo.addColumn("Valor");
        tabela.setModel(modelo);
        preencheTabelaCliente();
        this.setLocationRelativeTo(null);
    }
    public void preencheTabelaCliente(){
        List<Cliente> clientes = Persistencia.listar(new Cliente());
        int i = 0;
        DefaultTableModel tableModel = (DefaultTableModel)tabela.getModel();
        tableModel.setNumRows(0);
        Object[] linha = {1};
        
        for (Cliente cliente : clientes){
            if((!cliente.isRemovido())&&(!telaPai.clienteUsado(cliente))){
                tableModel.addRow(linha);
                tabela.setValueAt(cliente.getLogin(), i, 0);
                tabela.setValueAt(cliente.getNome(), i, 1);
                tabela.setValueAt(Inicial.dinheiro(cliente.getCredito()), i, 2);
                i++;
            }
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        botaoIncluirCredito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        botaoIncluirCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Incluir credito.png"))); // NOI18N
        botaoIncluirCredito.setText("Incluir Credito");
        botaoIncluirCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirCreditoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoIncluirCredito))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButton1)
                        .addGap(75, 75, 75)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoIncluirCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ValorHoraDAO vhd=new ValorHoraDAO();
        if (tabela.getSelectedRow() != -1){
            int linha = tabela.getSelectedRow();            
            List<Cliente> clientes = Persistencia.listar(new Cliente());                
            for (Cliente cliente: clientes){
                if (cliente.getLogin().equals((String)tabela.getValueAt(linha, 0))){
                    GerenciarUsoMaquina.validar(cliente, telaPai, this);
                }
            }   
        }                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoIncluirCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirCreditoActionPerformed
        if (tabela.getSelectedRow() != -1){
            int linha = tabela.getSelectedRow();
                if (tabela.getValueAt(linha, 0) != null){
                    Cliente cliente = GerenciarCliente.buscarCliente((String)tabela.getValueAt(linha, 0));
                    TelaIncluirCredito.main(cliente, telaPai, this);
                }
            
        }
    }//GEN-LAST:event_botaoIncluirCreditoActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
                String chave = jTextField1.getText().trim();
                List<Cliente> clientes = Persistencia.listar(new Cliente());

                if (chave.equals("")){
                    preencheTabelaCliente();
                }else {
                    DefaultTableModel tableModel = (DefaultTableModel)tabela.getModel();
                    tableModel.setNumRows(0);
                    Object[] linha = {1};
                    int i = 0;
                    for (Cliente cliente : clientes){
                        if(!cliente.isRemovido() && (cliente.getLogin().equalsIgnoreCase(chave)||(cliente.getNome().equalsIgnoreCase(chave)))){
                            tableModel.addRow(linha);
                            tabela.setValueAt(cliente.getLogin(), i, 0);
                            tabela.setValueAt(cliente.getNome(), i, 1);
                            tabela.setValueAt(Inicial.dinheiro(cliente.getCredito()), i, 2);
                                                 
                           
                            i++;
                        }
                    }
                }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], Inicial pai) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsoMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsoMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsoMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsoMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        telaPai=pai;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsoMaquina().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoIncluirCredito;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
